baseurl = "https://matthewkrump.com"
title = ""
copyright = "Copyright &copy; 2017 - Matthew Krump"
enableRobotsTXT = true
canonifyurls = true
theme = "kiera"

paginate = 10

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Matt Krump"
    github = "mkrump"
    gitlab = ""
    linkedin = "matthewkrump"
    facebook = ""
    twitter = ""
    instagram = ""



